# Welcome! Blueprint is controlled almost entirely through this file and that
# of the files themselves. Feel encouraged to use this as your default.
# The format is [TOML](https://github.com/toml-lang/toml).

# Workers let you define any partials or templates for your particular needs
# Options here are defined by the worker.
# Declaring a Resource implicitly loads it. To just use defaults do `[Worker.$WORKER]`
[Worker.Handlebars]
# The template directory. For now, this is a string. plans for arrays and globs.
templates = "./templates"
# TODO: Any toml data here will be unioned into the rendered data.
title = "An Example"
author = "Anony-mouse"
baseurl = "/"

# Delare a worker with no options.
[Worker.Copy]

# Tasks are units of work that must be done to build the blueprint.
# There is no guarantee of order, however you can be guaranteed that all
# resources and metadata will be loaded.
[Task.Styles]
# All values (including worker) are passed to the worker.
worker = "Copy"
source = "./styles/"
destination = "./styles/"

[Task.Pages]
worker = "Handlebars"
source = "./pages/"
destination = "./"
